CREATE TABLE USUARIOS (
id INT AUTO_INCREMENT PRIMARY KEY,
login VARCHAR(255) NOT NULL,
senha VARCHAR(255) NOT NULL,
balance DECIMAL(10,2) NOT NULL
);

-- ====USUARIOS DML ====

-- SELECIONAR TODOS OS USUARIOS:
SELECT * FROM USUARIOS;

-- SELECIONAR DADOS DO USUARIOS COM ID ESPECIFICO:
SELECT * FROM USUARIOS WHERE id =  ?;

--SELECIONAR DADOS DA AÇÃO COM NOME ESPECÍFICO
SELECT * FROM STOCKS WHERE name_stock = ?;

--SELECIONAR DADOS DO PAPEL COM NOME ESPECÍFICO
SELECT * FROM FIXED_INCOME WHERE name = ?;


